language: ruby
rvm:
  - 2.4.1
branches:
  only:
    - main
before_script: cp -rfv ./_includes .
script: JEKYLL_ENV=production bundle exec jekyll build --config ./_config.yml
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $JEKYLL_PAT
  local_dir: _site
  keep-history: true
  on:
    branch: main
    target_branch: gh-pages
