name: Deploy to Github Pages

on:
  push:
    branches:
      - main
    schedule:
      # redeploy every morning (that is 2:00 UTC) to update all unpublished pages
      - cron: "0 2 * * *"
    paths-ignore:
      - "README.md"
      - "LICENSE"
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: github-pages
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Caching for Bundler
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Build and deploy
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.JEKYLL_PAT }}
          jekyll_src: /
          gem_src: /
          target_branch: main
          # entryPoint:
          # args:
          # jekyll_env:
          # jekyll_build_options:
          # build_only: true
          # pre_build_commands: bundle exec jekyll doctor
